### ISSUE TITLE
Match v5 context to legacy converter context to back-support v5 plugins

### ISSUE THREAD

**Issue by RasPhilCo** [heroku/cli-engine#28]
https://github.com/heroku/cli/blob/master/context.go#L11

**Comment by ransombriggs** [comment]
I remember @RasPhilCo was concerned about polluting the context with a bunch of variables, and maybe can avoid that possibly if we only did this in the legacy commands through the converter though I have not looked at this portion too deeply yet to be completely sure.

When we were working on `apiUrl` I remember it being mildly awkward because we had to dig from `cli-engine` into `cli-engine-command` in order to add this to the context, I am wondering if it would be possible to move the legacy conversion back to the `cli-engine-command` so that we do not have to cross this boundary.

**Comment by ransombriggs** [comment]
I fixed up several attributes in https://github.com/heroku/cli-engine/pull/55
