### ISSUE TITLE
Some thoughts on cleaning up engine => engine-command interaction

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#35]
- Pass engine into engine command rather than requiring `../package.json` in engine-command
- Move the legacy command wrapping down into engine-command
- Move Topic.help into `cli-engine`, so it has all help logic (or vice-versa)
- Should `$ heroku` display help or a welcome screen? We got rid of welcome screen it seems

**Comment by jdx** [comment]
thanks for looking into these, I had been kind of moving things around a bit trying to find the right place for things, but I'm sure there could still be some cleanup. We'll want to do anything now too since we will have a tough time changing it later.

Some questions:

* you referring to this line? https://github.com/heroku/cli-engine-command/blob/master/src/config.js#L83 because the second part of that ternary is really only hit during tests for cli-engine-command. Or is it that you want to require the package.json in cli-engine?
* I had the legacy wrapping code in cli-engine-command originally but felt it was better for cli-engine since that way it wouldn't have to be duplicated for every cli-engine-command version we have out. Why do you think it''s better there?
* I'm +1 for this. The original reason was because overriding command help makes sense because you can customize it per plugin, but you can't override the topic list help because it shows up for every plugin. But we could put it all in there just for consistency anyways. Maybe we should put it all in cli-engine-command for later support for customization?
* `heroku dashboard` you mean? There should be a cli-engine.defaultCommand option, may not be working at the moment. I'll have to check.

**Comment by jdx** [comment]
can we close this now @ransombriggs?
